name: Deploy Flask App to EC2 via Terraform

on:
  push:
    paths:
      - 'app.py'     # only trigger when app.py changes
      - '.github/workflows/**'  # allow workflow self-editing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1  # match your main.tf

      - name: Terraform init
        run: terraform init

      - name: Taint instance so provisioners rerun
        run: terraform taint aws_instance.web

      - name: Terraform plan
        run: terraform plan -out=tfplan

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
